import type { ComfortCategoryKey, ComfortTone } from './chat.taxonomy';

export interface ComfortScriptSeed {
  category: ComfortCategoryKey;
  technique: string;
  triggerEmotion?: string;
  content: string;
  followUp?: string;
  tone?: ComfortTone;
  tags?: string[];
  priority?: number;
  isActive?: boolean;
}

/**
 * CBT / 正念 / 呼吸 / 着陆 / 共情 / 鼓励 / 转移 / 常规 话术库。
 * 面向特殊儿童（孤独症 / 多动症等），语言简短、具象、口语化，支持 {name} 占位个性化。
 * 共 58 条，覆盖 7 类负向与中性情绪的安抚场景。
 */
export const COMFORT_SCRIPTS: ComfortScriptSeed[] = [
  // ---------------- 呼吸放松 BREATHING（6） ----------------
  {
    category: 'BREATHING',
    technique: '4-7-8 呼吸',
    triggerEmotion: 'angry',
    content: '{name}，我们像吹蜡烛一样，先慢慢吸气 4 下，屏住 7 下，再用 8 下把气轻轻呼出来。跟着我做，好不好？',
    followUp: '再来一次，把肩膀也放松下来。',
    tone: 'calm',
    tags: ['呼吸', '放松', '愤怒'],
    priority: 6,
  },
  {
    category: 'BREATHING',
    technique: '气球呼吸',
    triggerEmotion: 'fear',
    content: '{name}，把手放在小肚子上，像在吹一个慢慢变大的气球——吸气鼓起来，呼气瘪下去。我们一起把气球吹大吧。',
    followUp: '气球吹大了，是不是觉得轻一点了？',
    tone: 'playful',
    tags: ['呼吸', '恐惧'],
    priority: 5,
  },
  {
    category: 'BREATHING',
    technique: '闻花香吹蜡烛',
    triggerEmotion: 'sad',
    content: '{name}，假装手里有一朵花，闻一闻——好香。再假装前面有一根蜡烛，呼——吹灭它。深吸，慢呼。',
    followUp: '要不要再闻一次花香？',
    tone: 'warm',
    tags: ['呼吸', '悲伤'],
    priority: 4,
  },
  {
    category: 'BREATHING',
    technique: '方块呼吸',
    content: '{name}，我们沿着一个小方块走：上边吸气，右边屏住，下边呼气，左边屏住。一、二、三、四，转一圈。',
    followUp: '你转了几圈啦？',
    tone: 'calm',
    tags: ['呼吸', '通用'],
    priority: 3,
  },
  {
    category: 'BREATHING',
    technique: '慢数呼吸',
    triggerEmotion: 'angry',
    content: '{name}，生气的时候，数着呼吸会很有帮助。吸气，一；呼气，二；吸气，三。慢慢来，不着急。',
    followUp: '数到几的时候，火气小一点了？',
    tone: 'calm',
    tags: ['呼吸', '愤怒'],
    priority: 4,
  },
  {
    category: 'BREATHING',
    technique: '星星呼吸',
    triggerEmotion: 'fear',
    content: '{name}，伸出手指，跟着星星的角画五角星：吸气画一条边，呼气画下一条边。星星画完，呼吸也稳了。',
    followUp: '再画一颗，你想画什么颜色的星星？',
    tone: 'playful',
    tags: ['呼吸', '恐惧'],
    priority: 3,
  },

  // ---------------- 着陆技术 GROUNDING（6） ----------------
  {
    category: 'GROUNDING',
    technique: '5-4-3-2-1 感官着陆',
    triggerEmotion: 'fear',
    content:
      '{name}，我们玩个找一找的游戏：说出你看到的 5 样东西、摸到的 4 样、听到的 3 样、闻到的 2 样、尝到的 1 样。先从看到的 5 样开始吧。',
    followUp: '你找到了哪些？一件一件告诉我。',
    tone: 'calm',
    tags: ['着陆', '恐惧', '焦虑'],
    priority: 6,
  },
  {
    category: 'GROUNDING',
    technique: '简化着陆',
    triggerEmotion: 'angry',
    content: '{name}，看看身边：说出一个红色的东西、一个软软的东西、一个会动的东西。把注意力放到它们身上。',
    followUp: '那个会动的东西是什么呀？',
    tone: 'calm',
    tags: ['着陆', '愤怒'],
    priority: 4,
  },
  {
    category: 'GROUNDING',
    technique: '脚踩大地',
    triggerEmotion: 'sad',
    content: '{name}，把两只脚稳稳踩在地上，感觉地板托着你。你不是飘着的，大地一直在接住你。',
    followUp: '脚底暖暖的，对不对？',
    tone: 'warm',
    tags: ['着陆', '悲伤'],
    priority: 4,
  },
  {
    category: 'GROUNDING',
    technique: '安全角落',
    triggerEmotion: 'fear',
    content: '{name}，想一想你最喜欢待的地方——家里的小被子？还是阳光下的窗台？闭上眼，那里很安全。',
    followUp: '那个角落有什么让你安心的？',
    tone: 'calm',
    tags: ['着陆', '恐惧'],
    priority: 5,
  },
  {
    category: 'GROUNDING',
    technique: '冷水触碰',
    triggerEmotion: 'angry',
    content: '{name}，如果可以，用凉水轻轻拍拍手腕或脸颊，凉凉的感觉能把火气往下压一压。',
    followUp: '凉凉的，是不是清醒一点了？',
    tone: 'calm',
    tags: ['着陆', '愤怒'],
    priority: 3,
  },
  {
    category: 'GROUNDING',
    technique: '抱抱自己',
    triggerEmotion: 'sad',
    content: '{name}，把两只手交叉抱住自己，轻轻拍拍肩膀，就像有人在温柔地抱着你。你值得被好好抱着。',
    followUp: '抱紧一点点，深呼吸一下。',
    tone: 'warm',
    tags: ['着陆', '悲伤', '自我安抚'],
    priority: 5,
  },

  // ---------------- 正念觉察 MINDFULNESS（8） ----------------
  {
    category: 'MINDFULNESS',
    technique: '身体扫描',
    content: '{name}，从脚趾开始，慢慢往上注意身体的每个部位：脚、腿、肚子、手、肩膀、头。哪里紧绷，就轻轻放松它。',
    followUp: '现在最放松的是哪里？',
    tone: 'calm',
    tags: ['正念', '通用'],
    priority: 3,
  },
  {
    category: 'MINDFULNESS',
    technique: '五感小探险',
    content: '{name}，我们当一分钟的小探险家：听一听现在有什么声音？是风，还是远处的人声？',
    followUp: '你听到了什么有趣的声音？',
    tone: 'playful',
    tags: ['正念', '通用'],
    priority: 3,
  },
  {
    category: 'MINDFULNESS',
    technique: '云朵观察',
    triggerEmotion: 'sad',
    content: '{name}，抬头看看窗外（或者闭上眼想象）：云慢慢飘，什么都没急着做。你也可以像云一样，慢慢飘。',
    followUp: '你希望自己是一片什么形状的云？',
    tone: 'calm',
    tags: ['正念', '悲伤'],
    priority: 3,
  },
  {
    category: 'MINDFULNESS',
    technique: '倾听三声',
    triggerEmotion: 'fear',
    content: '{name}，闭上眼睛，仔细听：能听到三种不同的声音吗？找一找，它们就在那里陪着你。',
    followUp: '哪一种声音让你最安心？',
    tone: 'calm',
    tags: ['正念', '恐惧'],
    priority: 4,
  },
  {
    category: 'MINDFULNESS',
    technique: '正念小食',
    content: '{name}，如果有小零食，慢慢咬一口，感受它在嘴里是什么味道、什么感觉。不急，好好尝一尝。',
    followUp: '它甜甜的还是咸咸的？',
    tone: 'warm',
    tags: ['正念', '通用'],
    priority: 2,
  },
  {
    category: 'MINDFULNESS',
    technique: '呼吸的颜色',
    triggerEmotion: 'angry',
    content: '{name}，想象你吸气时吸进的是蓝色的 calm 光，呼气时把红色的火气一点点吐出去。红越来越少，蓝越来越多。',
    followUp: '现在心里还剩多少红色？',
    tone: 'calm',
    tags: ['正念', '愤怒'],
    priority: 4,
  },
  {
    category: 'MINDFULNESS',
    technique: '此刻的星星',
    content: '{name}，今天有没有哪一瞬间，让你觉得还不错？哪怕很小很小，也可以把它当成一颗小星星收好。',
    followUp: '那颗星星是什么？',
    tone: 'warm',
    tags: ['正念', '感恩'],
    priority: 3,
  },
  {
    category: 'MINDFULNESS',
    technique: '感谢一件小事',
    triggerEmotion: 'sad',
    content: '{name}，我们找一件今天值得谢谢的事：一杯温水、一句问候、一个完成的动作，都可以。你先说一个。',
    followUp: '谢谢它，心里会不会暖一点？',
    tone: 'warm',
    tags: ['正念', '悲伤', '感恩'],
    priority: 3,
  },

  // ---------------- 认知行为疗法 CBT（10） ----------------
  {
    category: 'CBT',
    technique: '情绪命名',
    triggerEmotion: 'angry',
    content: '{name}，先给现在的感觉起个名字：是生气、委屈，还是着急？说出来，它就没那么可怕了。',
    followUp: '你给它起的名字是什么？',
    tone: 'warm',
    tags: ['CBT', '情绪识别', '愤怒'],
    priority: 6,
  },
  {
    category: 'CBT',
    technique: '想法泡泡',
    triggerEmotion: 'fear',
    content: '{name}，脑海里跑出来的念头，就像一个个肥皂泡泡。看着它飘过来，再看着它飘走，不用抓住它。',
    followUp: '刚才飘走的是哪一个泡泡？',
    tone: 'calm',
    tags: ['CBT', '想法', '恐惧'],
    priority: 5,
  },
  {
    category: 'CBT',
    technique: '换个想法',
    triggerEmotion: 'sad',
    content: '{name}，这件事除了「我很糟」，还能有别的看法吗？比如「我只是现在没做好，下次可以换个办法」。',
    followUp: '你还能想到另一种说法吗？',
    tone: 'warm',
    tags: ['CBT', '重构', '悲伤'],
    priority: 5,
  },
  {
    category: 'CBT',
    technique: '证据放大镜',
    triggerEmotion: 'angry',
    content: '{name}，拿个放大镜找找看：让我生气的这件事，真的全是别人的错吗？还是也有别的可能？',
    followUp: '放大镜里看到了什么新发现？',
    tone: 'calm',
    tags: ['CBT', '证据', '愤怒'],
    priority: 4,
  },
  {
    category: 'CBT',
    technique: '情绪温度计',
    triggerEmotion: 'angry',
    content: '{name}，我们给生气打个分：0 是不生气，10 是特别特别气。现在你大概在几？',
    followUp: '如果它降下来 1 分，会是因为什么？',
    tone: 'calm',
    tags: ['CBT', '量化', '愤怒'],
    priority: 5,
  },
  {
    category: 'CBT',
    technique: '我会犯错没关系',
    triggerEmotion: 'fear',
    content: '{name}，每个人都会出错，出错不等于糟糕。就像学走路会摔跤，站起来就好啦。',
    followUp: '你最近学会的哪件事，一开始也摔过？',
    tone: 'warm',
    tags: ['CBT', '容错', '恐惧'],
    priority: 4,
  },
  {
    category: 'CBT',
    technique: '最坏最好可能',
    triggerEmotion: 'sad',
    content: '{name}，我们一起想想：这件事最坏会怎样？最好会怎样？最可能发生的又是怎样？常常最可能发生的没那么糟。',
    followUp: '最可能发生的，你愿意接受吗？',
    tone: 'calm',
    tags: ['CBT', '预期', '悲伤'],
    priority: 3,
  },
  {
    category: 'CBT',
    technique: '思维记录三问',
    content: '{name}，遇到烦心事，问自己三句：发生了什么？我是怎么想的？换个想法会不会好受点？',
    followUp: '你愿意试试用这三问想一想吗？',
    tone: 'calm',
    tags: ['CBT', '通用'],
    priority: 3,
  },
  {
    category: 'CBT',
    technique: '情绪不是事实',
    triggerEmotion: 'angry',
    content: '{name}，「我很生气」是现在的感觉，不是「我是个坏孩子」。感觉会来，也会走，你还是你。',
    followUp: '感觉走了以后，你最想做什么？',
    tone: 'calm',
    tags: ['CBT', '去融合', '愤怒'],
    priority: 5,
  },
  {
    category: 'CBT',
    technique: '小步前进',
    triggerEmotion: 'sad',
    content: '{name}，事情太大做不完的时候，就先迈出一小步。哪怕只是把书翻开一页，也是前进。',
    followUp: '这一小步，你想先做哪一个？',
    tone: 'warm',
    tags: ['CBT', '行动', '悲伤'],
    priority: 4,
  },

  // ---------------- 情绪确认 VALIDATION（10） ----------------
  {
    category: 'VALIDATION',
    technique: '我看见你生气',
    triggerEmotion: 'angry',
    content: '{name}，我看见你现在很生气。生气是可以的，你的感觉很重要，我陪着你。',
    followUp: '要不要告诉我，是什么让你这么气？',
    tone: 'warm',
    tags: ['共情', '愤怒'],
    priority: 6,
  },
  {
    category: 'VALIDATION',
    technique: '害怕也没关系',
    triggerEmotion: 'fear',
    content: '{name}，害怕的时候，身体会发抖、想躲起来，这都很正常。害怕不等于胆小，我在这里。',
    followUp: '你怕的是哪一部分？我们一起看看。',
    tone: 'warm',
    tags: ['共情', '恐惧'],
    priority: 6,
  },
  {
    category: 'VALIDATION',
    technique: '难过是允许的',
    triggerEmotion: 'sad',
    content: '{name}，难过的时候，哭一哭、安静一会儿，都完全可以。不用假装开心，我陪你坐着。',
    followUp: '想说点什么，还是就想静静地待着？',
    tone: 'warm',
    tags: ['共情', '悲伤'],
    priority: 6,
  },
  {
    category: 'VALIDATION',
    technique: '你的感受很重要',
    content: '{name}，不管你现在是开心还是不开心，你的感受都值得被认真对待。我想听你的真实想法。',
    followUp: '你最想让我知道的是什么？',
    tone: 'warm',
    tags: ['共情', '通用'],
    priority: 4,
  },
  {
    category: 'VALIDATION',
    technique: '不想说话也可以',
    triggerEmotion: 'sad',
    content: '{name}，如果你现在不想说话，完全没关系。你可以用点头、摇头，或者就安静地待着，我都在。',
    followUp: '需要我陪你安静一会儿吗？',
    tone: 'calm',
    tags: ['共情', '沉默'],
    priority: 4,
  },
  {
    category: 'VALIDATION',
    technique: '我在这里陪你',
    triggerEmotion: 'fear',
    content: '{name}，你不是一个人。我就在这里，哪儿也不去，陪你把这一阵儿熬过去。',
    followUp: '要不要一起做个深呼吸？',
    tone: 'warm',
    tags: ['共情', '恐惧', '陪伴'],
    priority: 5,
  },
  {
    category: 'VALIDATION',
    technique: '生气不等于坏孩子',
    triggerEmotion: 'angry',
    content: '{name}，会生气的孩子不是坏孩子。生气只是心里在说「我不喜欢这样」。我们可以一起想办法。',
    followUp: '你不喜欢的是哪样？',
    tone: 'warm',
    tags: ['共情', '愤怒'],
    priority: 5,
  },
  {
    category: 'VALIDATION',
    technique: '紧张时可以停一下',
    triggerEmotion: 'fear',
    content: '{name}，紧张的时候，随时可以按下暂停键。停一停，喝口水，没人会怪你。',
    followUp: '要不要先停一下，我们慢慢来？',
    tone: 'calm',
    tags: ['共情', '恐惧'],
    priority: 4,
  },
  {
    category: 'VALIDATION',
    technique: '你已经很努力了',
    triggerEmotion: 'sad',
    content: '{name}，我知道你今天已经很努力了。努力过了还是觉得难，那也不是你的错。',
    followUp: '哪件事让你觉得最累？',
    tone: 'warm',
    tags: ['共情', '肯定', '悲伤'],
    priority: 5,
  },
  {
    category: 'VALIDATION',
    technique: '你的节奏由你决定',
    content: '{name}，别人快不快都不重要，你的节奏由你决定。慢一点，也没关系。',
    followUp: '你想按多慢的节奏来？',
    tone: 'warm',
    tags: ['共情', '通用'],
    priority: 3,
  },

  // ---------------- 鼓励赋能 ENCOURAGEMENT（8） ----------------
  {
    category: 'ENCOURAGEMENT',
    technique: '你很勇敢',
    triggerEmotion: 'fear',
    content: '{name}，能把自己的害怕说出来，本身就很勇敢。我为你骄傲。',
    followUp: '说出来之后，是不是轻了一点？',
    tone: 'warm',
    tags: ['鼓励', '恐惧'],
    priority: 5,
  },
  {
    category: 'ENCOURAGEMENT',
    technique: '一起试试看',
    triggerEmotion: 'sad',
    content: '{name}，这件事看起来有点难，但我们一起试试看，好不好？一步一步来。',
    followUp: '你希望我先陪你做哪一步？',
    tone: 'warm',
    tags: ['鼓励', '悲伤'],
    priority: 4,
  },
  {
    category: 'ENCOURAGEMENT',
    technique: '每小步都算数',
    content: '{name}，不要小看每一小步，它们加起来就是一大步。你今天已经走了好几步啦。',
    followUp: '你最想给自己鼓掌的是哪一步？',
    tone: 'warm',
    tags: ['鼓励', '通用'],
    priority: 4,
  },
  {
    category: 'ENCOURAGEMENT',
    technique: '你不是一个人',
    triggerEmotion: 'sad',
    content: '{name}，不论什么时候，你都不是一个人。爸爸妈妈、老师，还有我，都站在你这边。',
    followUp: '想到谁，你会觉得安心一点？',
    tone: 'warm',
    tags: ['鼓励', '悲伤', '陪伴'],
    priority: 5,
  },
  {
    category: 'ENCOURAGEMENT',
    technique: '我相信你可以',
    triggerEmotion: 'angry',
    content: '{name}，我知道你现在很火大，但我相信你能慢慢平静下来。你比自己想的更厉害。',
    followUp: '我们一起数到三，试着松口气？',
    tone: 'warm',
    tags: ['鼓励', '愤怒'],
    priority: 4,
  },
  {
    category: 'ENCOURAGEMENT',
    technique: '停一下也没关系',
    triggerEmotion: 'angry',
    content: '{name}，累了就停一下，这不是放弃，是给自己充电。充好电再继续，会更轻松。',
    followUp: '你想怎么给自己充个电？',
    tone: 'calm',
    tags: ['鼓励', '愤怒'],
    priority: 3,
  },
  {
    category: 'ENCOURAGEMENT',
    technique: '你做得很好',
    content: '{name}，刚才你愿意和我说话、愿意试一试，这就做得很好。我看见了。',
    followUp: '被夸的时候，嘴角是不是翘起来了？',
    tone: 'warm',
    tags: ['鼓励', '通用'],
    priority: 4,
  },
  {
    category: 'ENCOURAGEMENT',
    technique: '我们慢慢来',
    triggerEmotion: 'fear',
    content: '{name}，不用一下子全做好，我们慢慢来。今天比昨天多走一步，就是胜利。',
    followUp: '今天你想先慢慢做哪一件？',
    tone: 'warm',
    tags: ['鼓励', '恐惧'],
    priority: 4,
  },

  // ---------------- 转移注意 DISTRACTION（6） ----------------
  {
    category: 'DISTRACTION',
    technique: '数数游戏',
    triggerEmotion: 'angry',
    content: '{name}，我们来数数游戏：从 1 数到 20，每数一个数就跺一下脚。一、二、三……',
    followUp: '数到几了？继续！',
    tone: 'playful',
    tags: ['转移', '愤怒'],
    priority: 4,
  },
  {
    category: 'DISTRACTION',
    technique: '唱一首歌',
    triggerEmotion: 'sad',
    content: '{name}，我们一起唱首喜欢的歌吧！你最爱哪首？唱出来，心情会跟着旋律飞起来。',
    followUp: '下一句是什么？我跟着你唱。',
    tone: 'playful',
    tags: ['转移', '悲伤'],
    priority: 4,
  },
  {
    category: 'DISTRACTION',
    technique: '找颜色',
    triggerEmotion: 'fear',
    content: '{name}，玩个找颜色：在房间里找 3 个蓝色的东西，再找 2 个黄色的东西。找到了吗？',
    followUp: '你找到的蓝色东西是什么？',
    tone: 'playful',
    tags: ['转移', '恐惧'],
    priority: 4,
  },
  {
    category: 'DISTRACTION',
    technique: '讲个谜语',
    content: '{name}，我出个谜语：什么东西越洗越脏？（答案是水！）你猜对了吗？要不要你来出一个考我？',
    followUp: '轮到你出题啦，是什么？',
    tone: 'playful',
    tags: ['转移', '通用'],
    priority: 3,
  },
  {
    category: 'DISTRACTION',
    technique: '跳一跳',
    triggerEmotion: 'angry',
    content: '{name}，原地跳三下！把心里那股劲儿，变成小弹簧「蹦」出去。一、二、三，跳！',
    followUp: '跳完是不是轻松一点点？',
    tone: 'playful',
    tags: ['转移', '运动', '愤怒'],
    priority: 4,
  },
  {
    category: 'DISTRACTION',
    technique: '说说喜欢的动物',
    triggerEmotion: 'sad',
    content: '{name}，说说你最喜欢的动物吧！它长什么样，为什么喜欢它？想象和它一起玩。',
    followUp: '如果它能说话，它会对你说什么？',
    tone: 'playful',
    tags: ['转移', '悲伤'],
    priority: 3,
  },

  // ---------------- 行为引导 ROUTINE（4） ----------------
  {
    category: 'ROUTINE',
    technique: '先做一件事',
    triggerEmotion: 'angry',
    content: '{name}，我们现在只做一件事：把桌上的铅笔摆整齐。做完这一件，再想下一件。',
    followUp: '铅笔摆好了吗？很棒，下一件是什么？',
    tone: 'calm',
    tags: ['常规', '行动', '愤怒'],
    priority: 4,
  },
  {
    category: 'ROUTINE',
    technique: '整理小任务',
    content: '{name}，我们把大任务拆成小豆子：先吃一颗豆——做第一步，再吃一颗——做第二步。一颗一颗来。',
    followUp: '第一颗豆，你想先吃哪一颗？',
    tone: 'calm',
    tags: ['常规', '通用'],
    priority: 3,
  },
  {
    category: 'ROUTINE',
    technique: '安静角约定',
    triggerEmotion: 'fear',
    content: '{name}，我们约定一个「安静角」：难过或害怕时，就去那里抱抱玩偶、听听音乐，谁都不会打扰你。',
    followUp: '你的安静角想放什么？',
    tone: 'calm',
    tags: ['常规', '安全感', '恐惧'],
    priority: 4,
  },
  {
    category: 'ROUTINE',
    technique: '深呼吸再决定',
    triggerEmotion: 'angry',
    content: '{name}，在发脾气做决定前，先深呼吸三次。很多麻烦，都是在那三口气里消失的。',
    followUp: '三口气吸完，还想做刚才那件事吗？',
    tone: 'calm',
    tags: ['常规', '冲动控制', '愤怒'],
    priority: 4,
  },
];
