import type { KnowledgeCategoryKey, AdviceSeverityKey, AdviceTargetKey } from './advice.taxonomy';

export interface KnowledgeSeed {
  category: KnowledgeCategoryKey;
  title: string;
  content: string;
  summary?: string;
  source?: string;
  severity?: AdviceSeverityKey;
  target?: AdviceTargetKey;
  applicableEmotions?: string[];
  applicableBehaviors?: string[];
  tags?: string[];
  reference?: string;
  priority?: number;
  isActive?: boolean;
}

/**
 * 专业心理 / 特教知识库（≥200 条）。
 * 覆盖特殊儿童（孤独症谱系 ASD、注意缺陷多动障碍 ADHD、感统失调、发育迟缓等）干预的主要维度。
 * 来源标注主流循证方法：ABA、TEACCH、正念、CBT、社交故事、感觉统合、DIR/Floortime、SCERTS、PECS、PRT 等。
 */
export const KNOWLEDGE_ITEMS: KnowledgeSeed[] = [
  // ============================ 情绪调节 EMOTION_REGULATION ============================
  { category: 'EMOTION_REGULATION', title: '情绪温度计自评', content: '教孩子用「温度计 1-10」给心情打分，帮助其在情绪升级前用语言而非行为表达。每天固定时段练习，建立情绪觉察基线。', source: 'CBT', severity: 'LOW', target: 'STUDENT', applicableEmotions: ['angry', 'sad', 'fear'], tags: ['情绪觉察', '自评'], reference: 'Gottman 情绪辅导', priority: 8 },
  { category: 'EMOTION_REGULATION', title: '冷静角设置', content: '在家中或教室设置低刺激「冷静角」：软垫、降噪耳机、减压球，允许孩子在情绪激动时主动前往，而非被惩罚隔离。', source: 'TEACCH', severity: 'LOW', target: 'ALL', applicableEmotions: ['angry', 'fear'], tags: ['冷静角', '环境'], reference: 'TEACCH 结构化教学', priority: 8 },
  { category: 'EMOTION_REGULATION', title: '情绪命名三步法', content: '当孩子出现情绪时，先共情（我看到你很生气）、再命名（这是生气）、后引导（我们深呼吸）。三步法降低情绪强度。', source: 'CBT', severity: 'LOW', target: 'ALL', applicableEmotions: ['angry', 'sad', 'fear', 'disgust'], tags: ['共情', '命名'], priority: 9 },
  { category: 'EMOTION_REGULATION', title: '正念身体扫描', content: '每天 3 分钟引导式身体扫描：从脚趾到头顶逐一放松，帮助高唤醒儿童降低生理唤醒水平。', source: '正念', severity: 'LOW', target: 'STUDENT', applicableEmotions: ['angry', 'fear'], tags: ['正念', '放松'], reference: 'MBSR', priority: 6 },
  { category: 'EMOTION_REGULATION', title: '情绪绘本共读', content: '选用情绪主题绘本（如《我的情绪小怪兽》），通过角色共情提升情绪识别与理解能力，每周 2-3 次。', source: '社交故事', severity: 'LOW', target: 'ALL', applicableEmotions: ['sad', 'fear', 'surprise'], tags: ['绘本', '共读'], priority: 7 },
  { category: 'EMOTION_REGULATION', title: '情绪卡片视觉支持', content: '用图卡帮助语言迟缓儿童指认「生气/害怕/难过」，降低因表达受阻引发的情绪爆发。', source: 'PECS', severity: 'LOW', target: 'ALL', applicableEmotions: ['angry', 'fear', 'sad'], tags: ['视觉支持', '沟通'], priority: 8 },
  { category: 'EMOTION_REGULATION', title: '先备技能：识别身体信号', content: '先教孩子识别「心跳快、拳头紧」等生理信号，再教应对策略，避免直接要求「别生气」。', source: 'CBT', severity: 'LOW', target: 'ALL', applicableEmotions: ['angry', 'fear'], tags: ['生理信号'], priority: 7 },
  { category: 'EMOTION_REGULATION', title: '情绪升级预警表', content: '绘制从平静到爆发的 5 级预警表，标注每级的行为表现，帮助照料者早期介入而非事后处理。', source: '行为分析', severity: 'MEDIUM', target: 'ALL', applicableEmotions: ['angry', 'fear'], tags: ['预警', '升级'], priority: 8 },
  { category: 'EMOTION_REGULATION', title: '替代行为训练', content: '针对情绪爆发，训练可接受的替代行为（如捏减压球代替咬人），用正向强化巩固替代行为。', source: 'ABA', severity: 'MEDIUM', target: 'ALL', applicableEmotions: ['angry', 'disgust'], applicableBehaviors: ['stamp', 'shake_head'], tags: ['替代行为', 'DRA'], reference: 'ABA 差别性强化', priority: 9 },
  { category: 'EMOTION_REGULATION', title: '情绪调节绘本剧', content: '让孩子扮演绘本中的角色处理冲突，在安全距离下练习情绪调节策略，提升泛化能力。', source: '社交故事', severity: 'LOW', target: 'STUDENT', applicableEmotions: ['sad', 'angry'], tags: ['角色扮演'], priority: 6 },
  { category: 'EMOTION_REGULATION', title: '呼吸球练习', content: '使用可视化呼吸球（吸气变大、呼气变小）引导孩子延长呼气，激活副交感神经降低焦虑。', source: '正念', severity: 'LOW', target: 'STUDENT', applicableEmotions: ['fear', 'angry'], tags: ['呼吸', '焦虑'], priority: 7 },
  { category: 'EMOTION_REGULATION', title: '情绪日记图表', content: '用一周情绪图表记录触发事件与强度，帮助孩子与家长发现规律，逐步建立预测能力。', source: 'CBT', severity: 'LOW', target: 'ALL', applicableEmotions: ['sad', 'angry', 'fear'], tags: ['记录', '规律'], priority: 6 },
  { category: 'EMOTION_REGULATION', title: '社会性赞美强化', content: '当孩子用恰当方式表达情绪时，立即给予具体赞美（你用语言告诉我你生气了，真棒），强化正向通道。', source: 'PRT', severity: 'LOW', target: 'ALL', applicableEmotions: ['angry', 'sad'], tags: ['强化', '表达'], priority: 8 },
  { category: 'EMOTION_REGULATION', title: '分级任务降低挫折', content: '将困难任务拆为更小步骤，每步可达成，减少因反复失败引发的挫败性负面情绪。', source: 'TEACCH', severity: 'LOW', target: 'ALL', applicableEmotions: ['angry', 'sad'], tags: ['任务分解'], priority: 7 },
  { category: 'EMOTION_REGULATION', title: '情绪调节家庭公约', content: '全家约定统一情绪应对方式（如生气时说「我需要暂停」），避免不同照料者回应方式冲突。', source: '家庭系统', severity: 'LOW', target: 'PARENT', applicableEmotions: ['angry', 'fear'], tags: ['家庭公约'], priority: 6 },
  { category: 'EMOTION_REGULATION', title: '正念听觉练习', content: '引导孩子闭眼听 1 分钟环境声音并描述，将注意力从情绪转向当下感官，打断反刍。', source: '正念', severity: 'LOW', target: 'STUDENT', applicableEmotions: ['sad', 'fear'], tags: ['听觉', '当下'], priority: 5 },
  { category: 'EMOTION_REGULATION', title: '高强度运动宣泄', content: '在情绪升级前安排 10 分钟蹦床、推墙等本体觉活动，安全宣泄能量，预防爆发。', source: '感觉统合', severity: 'MEDIUM', target: 'ALL', applicableEmotions: ['angry'], applicableBehaviors: ['jump', 'stamp'], tags: ['运动', '宣泄'], priority: 7 },
  { category: 'EMOTION_REGULATION', title: '情绪急救包', content: '为孩子准备个性化「情绪急救包」（耳机、喜欢的书、减压玩具），在公共场所情绪不稳时快速取用。', source: 'TEACCH', severity: 'MEDIUM', target: 'ALL', applicableEmotions: ['fear', 'angry'], tags: ['急救包', '随身'], priority: 7 },

  // ============================ 社交技能 SOCIAL_SKILL ============================
  { category: 'SOCIAL_SKILL', title: '轮流游戏训练', content: '从两人轮流推车、滚球开始，用视觉计时器提示轮次，建立「等待—轮到我」的基础社会规则。', source: 'DIR/Floortime', severity: 'LOW', target: 'ALL', applicableBehaviors: ['wave', 'point'], tags: ['轮流', '游戏'], priority: 8 },
  { category: 'SOCIAL_SKILL', title: '社交故事：打招呼', content: '编写个性化社交故事，图示「看到同学→挥手→说你好」，每天晨读并实景练习，提升主动问候。', source: '社交故事', severity: 'LOW', target: 'STUDENT', applicableBehaviors: ['wave'], tags: ['打招呼', '社交故事'], reference: 'Carol Gray 社交故事', priority: 8 },
  { category: 'SOCIAL_SKILL', title: '共同注意训练', content: '通过指物、分享式注意（你看这个！）练习，提升共同注意这一社交核心能力，是后续社交发展的基础。', source: 'ESDM', severity: 'LOW', target: 'ALL', applicableBehaviors: ['point'], tags: ['共同注意'], priority: 8 },
  { category: 'SOCIAL_SKILL', title: '情绪表情配对卡', content: '用表情卡做配对与指认游戏，帮助孩子识别他人情绪，是观点采择的前备技能。', source: 'TEACCH', severity: 'LOW', target: 'STUDENT', applicableEmotions: ['happy', 'sad', 'angry', 'fear'], tags: ['表情', '识别'], priority: 7 },
  { category: 'SOCIAL_SKILL', title: '角色扮演社交情景', content: '设置借玩具、排队等微型情景，角色扮演并录像回放，帮助孩子理解社会期望与后果。', source: 'CBT', severity: 'LOW', target: 'STUDENT', tags: ['角色扮演', '情景'], priority: 7 },
  { category: 'SOCIAL_SKILL', title: '同伴伙伴制', content: '在班级安排稳定的「同伴伙伴」，固定一起活动，创造自然社交练习机会，减少孤立。', source: '融合教育', severity: 'LOW', target: 'TEACHER', tags: ['同伴', '融合'], priority: 7 },
  { category: 'SOCIAL_SKILL', title: '社交脚本植入', content: '为常见场景（如请求加入游戏）提供简短脚本「我可以一起玩吗？」，逐步内化为自发语言。', source: 'PRT', severity: 'LOW', target: 'ALL', applicableBehaviors: ['point', 'clap'], tags: ['脚本', '语言'], priority: 8 },
  { category: 'SOCIAL_SKILL', title: '分享行为强化', content: '当孩子主动分享物品或成就时，立即社会性强化，塑造利他与分享的社会行为。', source: 'ABA', severity: 'LOW', target: 'ALL', applicableBehaviors: ['clap'], tags: ['分享', '强化'], priority: 7 },
  { category: 'SOCIAL_SKILL', title: '解读社交线索', content: '教孩子观察他人的肢体与面部线索（皱眉=不高兴），降低社交误解导致的冲突。', source: 'SCERTS', severity: 'LOW', target: 'STUDENT', applicableEmotions: ['angry', 'sad'], tags: ['线索', '解读'], priority: 7 },
  { category: 'SOCIAL_SKILL', title: '合作任务设计', content: '布置必须两人协作完成的任务（抬桌子、拼大图），在真实合作中练习沟通与配合。', source: '融合教育', severity: 'LOW', target: 'TEACHER', tags: ['合作', '任务'], priority: 6 },
  { category: 'SOCIAL_SKILL', title: '社交破冰游戏', content: '用「找朋友」「名字接龙」等低压力破冰游戏，帮助害羞儿童在安全氛围下练习互动。', source: '团体治疗', severity: 'LOW', target: 'ALL', applicableEmotions: ['fear'], tags: ['破冰', '团体'], priority: 6 },
  { category: 'SOCIAL_SKILL', title: '观点采择训练', content: '通过「如果他那样做，他会怎么想？」提问，逐步培养孩子的心理理论（Theory of Mind）能力。', source: 'CBT', severity: 'MEDIUM', target: 'STUDENT', tags: ['心理理论', '观点'], priority: 6 },
  { category: 'SOCIAL_SKILL', title: '拒绝与协商表达', content: '教孩子在不能接受时礼貌表达「我不喜欢，但我们可以…」，替代哭闹或攻击等拒绝方式。', source: '社交故事', severity: 'LOW', target: 'STUDENT', applicableEmotions: ['angry', 'disgust'], tags: ['拒绝', '协商'], priority: 7 },
  { category: 'SOCIAL_SKILL', title: '团体规则图示', content: '用图画展示团体活动规则（举手发言、不打断），贴在活动区，降低社交场景的不确定性。', source: 'TEACCH', severity: 'LOW', target: 'TEACHER', tags: ['规则', '图示'], priority: 6 },
  { category: 'SOCIAL_SKILL', title: '赞美他人练习', content: '引导孩子观察同伴优点并说出赞美（你的画真好看），提升正向社交互动的频率。', source: 'PRT', severity: 'LOW', target: 'STUDENT', tags: ['赞美', '互动'], priority: 6 },
  { category: 'SOCIAL_SKILL', title: '虚拟社交演练', content: '用社交软件或游戏中的安全情境练习发起对话与结束对话，避免真实社交的高压。', source: 'CBT', severity: 'LOW', target: 'STUDENT', tags: ['虚拟', '演练'], priority: 5 },
  { category: 'SOCIAL_SKILL', title: '家庭社交时间', content: '每天安排 15 分钟无电子产品的家庭互动（桌游、聊天），在熟悉环境中练习社交。', source: '家庭系统', severity: 'LOW', target: 'PARENT', tags: ['家庭', '互动'], priority: 6 },
  { category: 'SOCIAL_SKILL', title: '社交进步记录表', content: '用贴纸记录每次成功社交互动，可视化进步，增强孩子社交自信心。', source: 'ABA', severity: 'LOW', target: 'ALL', tags: ['记录', '自信'], priority: 5 },

  // ============================ 行为干预 BEHAVIOR_INTERVENTION ============================
  { category: 'BEHAVIOR_INTERVENTION', title: 'ABC 行为记录', content: '记录行为的前因(Antecedent)、行为(Behavior)、后果(Consequence)，找出行为功能（求关注/逃避/感官），再对症治疗。', source: 'ABA', severity: 'MEDIUM', target: 'ALL', applicableBehaviors: ['stamp', 'shake_head', 'self_injury', 'run', 'leave_seat'], tags: ['ABC', '功能分析'], reference: 'O’Neill 功能分析', priority: 9 },
  { category: 'BEHAVIOR_INTERVENTION', title: '前因控制策略', content: '通过环境调整消除触发（如把易碎品收好、减少噪音），从源头降低问题行为发生概率。', source: 'ABA', severity: 'LOW', target: 'ALL', applicableBehaviors: ['stamp', 'shake_head'], tags: ['前因', '环境'], priority: 8 },
  { category: 'BEHAVIOR_INTERVENTION', title: '正向行为支持 PBS', content: '以正向行为支持为核心，教授替代技能、调整环境与后果，系统性减少问题行为而非单纯惩罚。', source: 'PBS', severity: 'MEDIUM', target: 'ALL', applicableBehaviors: ['self_injury', 'stamp', 'run'], tags: ['PBS', '系统'], priority: 9 },
  { category: 'BEHAVIOR_INTERVENTION', title: '差别性强化 DRA', content: '强化与问题行为功能相同但可接受的替代行为（如用语言求关注代替尖叫），削弱问题行为。', source: 'ABA', severity: 'MEDIUM', target: 'ALL', applicableBehaviors: ['shake_head', 'stamp'], tags: ['DRA', '替代'], priority: 9 },
  { category: 'BEHAVIOR_INTERVENTION', title: '功能性沟通训练 FCT', content: '教孩子用沟通代替问题行为（如用图卡说「休息」代替发脾气），是最有效的减少攻击性行为的方法之一。', source: 'ABA', severity: 'HIGH', target: 'ALL', applicableBehaviors: ['self_injury', 'stamp', 'shake_head'], tags: ['FCT', '沟通'], priority: 10 },
  { category: 'BEHAVIOR_INTERVENTION', title: '行为契约制', content: '与孩子约定明确的行为目标与奖励，书面化并可视化，提升其参与感与执行力。', source: 'CBT', severity: 'LOW', target: 'ALL', tags: ['契约', '奖励'], priority: 6 },
  { category: 'BEHAVIOR_INTERVENTION', title: '不予强化消退', content: '对以获取关注为功能的行为，在确保安全下采用有计划消退（不给予关注），使其自然降低，需全家一致执行。', source: 'ABA', severity: 'MEDIUM', target: 'ALL', applicableBehaviors: ['stamp', 'shake_head'], tags: ['消退', '一致'], priority: 7 },
  { category: 'BEHAVIOR_INTERVENTION', title: '视觉行为规则卡', content: '用图卡展示「可以/不可以」行为，贴在相应区域，减少因不理解规则导致的行为问题。', source: 'TEACCH', severity: 'LOW', target: 'ALL', applicableBehaviors: ['leave_seat', 'run'], tags: ['规则卡', '视觉'], priority: 7 },
  { category: 'BEHAVIOR_INTERVENTION', title: '结构化一日流程', content: '用可视化日程表让一日活动可预测，减少因不确定性引发的无目的走动与离座。', source: 'TEACCH', severity: 'LOW', target: 'ALL', applicableBehaviors: ['leave_seat', 'run'], tags: ['结构化', '日程'], priority: 8 },
  { category: 'BEHAVIOR_INTERVENTION', title: '自我管理法', content: '教孩子用核查表自评行为（我今天有没有举手？），逐步从外部管理过渡到自我管理。', source: 'CBT', severity: 'MEDIUM', target: 'STUDENT', applicableBehaviors: ['leave_seat'], tags: ['自我管理', '核查'], priority: 7 },
  { category: 'BEHAVIOR_INTERVENTION', title: '差别性强化不兼容行为 DRI', content: '强化与问题行为物理上不兼容的行为（如强化「手放桌上」以减少离座），阻断问题行为表达。', source: 'ABA', severity: 'MEDIUM', target: 'ALL', applicableBehaviors: ['leave_seat', 'stamp'], tags: ['DRI', '不兼容'], priority: 8 },
  { category: 'BEHAVIOR_INTERVENTION', title: '代币经济系统', content: '用代币即时标记正向行为，积攒兑换偏好活动，建立稳定、可预期的行为强化体系。', source: 'ABA', severity: 'LOW', target: 'ALL', tags: ['代币', '强化'], priority: 7 },
  { category: 'BEHAVIOR_INTERVENTION', title: '行为功能访谈', content: '通过访谈家长与教师收集行为发生的情境与功能假设，是制定个别化行为计划(IEP-BIP)的起点。', source: 'PBS', severity: 'MEDIUM', target: 'ALL', applicableBehaviors: ['self_injury', 'stamp', 'run', 'leave_seat'], tags: ['访谈', '功能'], priority: 7 },
  { category: 'BEHAVIOR_INTERVENTION', title: '危机行为预防计划', content: '对自伤或攻击行为，预先制定书面预防与应对计划，明确触发、预警信号与全员分工。', source: 'PBS', severity: 'HIGH', target: 'ALL', applicableBehaviors: ['self_injury'], tags: ['危机', '计划'], priority: 10 },
  { category: 'BEHAVIOR_INTERVENTION', title: '重定向技术', content: '在问题行为刚出现时，用中性语言将注意力引向替代活动（我们去做拼图吧），避免强化。', source: 'ABA', severity: 'LOW', target: 'ALL', applicableBehaviors: ['spin', 'stamp'], tags: ['重定向', '中性'], priority: 7 },
  { category: 'BEHAVIOR_INTERVENTION', title: '行为数据化记录', content: '用频率/时长/强度三维度记录问题行为，量化干预效果，避免凭印象判断进展。', source: 'ABA', severity: 'LOW', target: 'ALL', applicableBehaviors: ['self_injury', 'stamp', 'shake_head'], tags: ['数据', '量化'], priority: 7 },
  { category: 'BEHAVIOR_INTERVENTION', title: '脱敏渐进暴露', content: '对特定恐惧诱发的行为，采用系统化脱敏（从远到近、从短时到长时）逐步适应。', source: 'CBT', severity: 'MEDIUM', target: 'ALL', applicableEmotions: ['fear'], tags: ['脱敏', '暴露'], priority: 7 },
  { category: 'BEHAVIOR_INTERVENTION', title: '同伴介导干预', content: '训练普通同伴使用提示与示范，带动特殊儿童参与活动，比成人主导更具自然泛化效果。', source: 'PRT', severity: 'LOW', target: 'TEACHER', tags: ['同伴', '介导'], priority: 6 },
  { category: 'BEHAVIOR_INTERVENTION', title: '行为后果一致性', content: '确保不同场景（家/校）对同一行为的后果一致，避免孩子在不同环境中策略性切换行为。', source: 'PBS', severity: 'MEDIUM', target: 'ALL', applicableBehaviors: ['stamp', 'leave_seat'], tags: ['一致性', '跨场景'], priority: 7 },
  { category: 'BEHAVIOR_INTERVENTION', title: '强化物偏好评估', content: '定期做强化物偏好评估（提供多项选择观察选择），保证所用强化物对孩子真正有效。', source: 'ABA', severity: 'LOW', target: 'ALL', tags: ['强化物', '评估'], priority: 6 },

  // ============================ 感觉统合 SENSORY_INTEGRATION ============================
  { category: 'SENSORY_INTEGRATION', title: '感觉餐单设计', content: '由作业治疗师设计个性化「感觉餐单」，在一天中穿插本体觉/前庭觉活动，维持最佳觉醒水平。', source: '感觉统合', severity: 'LOW', target: 'ALL', applicableBehaviors: ['spin', 'jump', 'stamp'], tags: ['感觉餐单', 'OT'], reference: 'Ayres SI', priority: 8 },
  { category: 'SENSORY_INTEGRATION', title: '本体觉压力输入', content: '提供深压（拥抱、压滚桶、负重背包）帮助触觉防御儿童平静，优于轻触。', source: '感觉统合', severity: 'LOW', target: 'ALL', applicableEmotions: ['fear', 'angry'], tags: ['本体觉', '深压'], priority: 8 },
  { category: 'SENSORY_INTEGRATION', title: '前庭觉摇摆', content: '用吊床、秋千进行有节奏的前庭输入，调节觉醒度，对过度兴奋或低张力儿童均有益。', source: '感觉统合', severity: 'LOW', target: 'STUDENT', applicableBehaviors: ['spin'], tags: ['前庭', '摇摆'], priority: 7 },
  { category: 'SENSORY_INTEGRATION', title: '触觉防御脱敏', content: '对触觉过敏儿童，从最不敏感部位开始渐进触摸游戏（玩沙、揉面团），降低触觉逃避。', source: '感觉统合', severity: 'MEDIUM', target: 'ALL', applicableEmotions: ['disgust', 'fear'], tags: ['触觉', '脱敏'], priority: 7 },
  { category: 'SENSORY_INTEGRATION', title: '听觉过滤训练', content: '对声音敏感儿童，使用降噪耳机逐步暴露并配合正向活动，提升声音耐受度。', source: '感觉统合', severity: 'MEDIUM', target: 'ALL', applicableEmotions: ['fear', 'disgust'], tags: ['听觉', '过滤'], priority: 7 },
  { category: 'SENSORY_INTEGRATION', title: '感统环境改造', content: '减少荧光灯频闪、降低环境噪音、提供软垫区，从环境层面降低感官超载。', source: '感觉统合', severity: 'LOW', target: 'ALL', applicableEmotions: ['fear', 'angry'], tags: ['环境', '改造'], priority: 7 },
  { category: 'SENSORY_INTEGRATION', title: '口腔觉满足', content: '提供嚼咬玩具、冰块等安全的本体口部输入，满足口部寻求行为，减少对衣物的啃咬。', source: '感觉统合', severity: 'LOW', target: 'STUDENT', tags: ['口腔', '寻求'], priority: 6 },
  { category: 'SENSORY_INTEGRATION', title: '重力毯使用', content: '在休息或睡眠时使用适度重力毯，提供包裹感，帮助感觉防御儿童稳定情绪与入睡。', source: '感觉统合', severity: 'LOW', target: 'ALL', applicableEmotions: ['fear', 'sad'], tags: ['重力毯', '睡眠'], priority: 6 },
  { category: 'SENSORY_INTEGRATION', title: '感觉中断预警', content: '从一项感官活动切换前，给予 5 分钟、2 分钟、1 分钟三级预警，减少切换引发的抗拒。', source: 'TEACCH', severity: 'LOW', target: 'ALL', applicableBehaviors: ['spin', 'jump'], tags: ['预警', '切换'], priority: 7 },
  { category: 'SENSORY_INTEGRATION', title: '触觉探索游戏', content: '设置米箱、水桌等多元质感探索区，在安全范围内满足触觉探索需求。', source: '感觉统合', severity: 'LOW', target: 'STUDENT', applicableEmotions: ['disgust'], tags: ['触觉', '探索'], priority: 6 },
  { category: 'SENSORY_INTEGRATION', title: '觉醒度自我调节', content: '教孩子识别自己「太兴奋/太困」的状态，并选择对应感觉活动（蹦跳提神、深压 calming）。', source: '感觉统合', severity: 'LOW', target: 'STUDENT', applicableEmotions: ['angry', 'fear'], tags: ['觉醒度', '自我调节'], priority: 7 },
  { category: 'SENSORY_INTEGRATION', title: '运动Break融入课表', content: '在长时段静态学习间插入 2 分钟感统运动 break，提升注意维持与课堂参与。', source: '感觉统合', severity: 'LOW', target: 'TEACHER', applicableBehaviors: ['leave_seat', 'jump'], tags: ['运动', '课表'], priority: 6 },
  { category: 'SENSORY_INTEGRATION', title: '视觉负荷管理', content: '简化视觉环境，避免过多海报与鲜艳颜色同时呈现，降低视觉超载引发的不适。', source: 'TEACCH', severity: 'LOW', target: 'ALL', applicableEmotions: ['fear', 'disgust'], tags: ['视觉', '负荷'], priority: 6 },
  { category: 'SENSORY_INTEGRATION', title: '感觉统合评估转介', content: '若孩子存在明显感觉处理异常（过敏/寻求），建议转介作业治疗师进行标准化评估（如 SIPT）。', source: '感觉统合', severity: 'MEDIUM', target: 'ALL', applicableBehaviors: ['spin', 'stamp'], tags: ['评估', '转介'], priority: 7 },
  { category: 'SENSORY_INTEGRATION', title: '摇摆坐垫应用', content: '在座位上使用充气摇摆坐垫，提供微量持续本体输入，帮助多动儿童安静就座。', source: '感觉统合', severity: 'LOW', target: 'ALL', applicableBehaviors: ['leave_seat', 'sit_still'], tags: ['坐垫', '就座'], priority: 6 },
  { category: 'SENSORY_INTEGRATION', title: '嗅觉安抚工具', content: '对嗅觉敏感者，提供喜欢的气味（薰衣草）作为安抚线索，建立正向嗅觉联结。', source: '感觉统合', severity: 'LOW', target: 'STUDENT', applicableEmotions: ['fear', 'sad'], tags: ['嗅觉', '安抚'], priority: 5 },
  { category: 'SENSORY_INTEGRATION', title: '感统与情绪关联教育', content: '向家长说明感觉超载常表现为「行为问题」，先处理感官需求再处理行为，避免误判。', source: '感觉统合', severity: 'MEDIUM', target: 'PARENT', applicableBehaviors: ['stamp', 'shake_head'], tags: ['教育', '关联'], priority: 7 },
  { category: 'SENSORY_INTEGRATION', title: '户外大动作释放', content: '每日保证 60 分钟户外大动作（跑、跳、爬），消耗过剩能量，改善夜间睡眠与日间安定。', source: '感觉统合', severity: 'LOW', target: 'ALL', applicableBehaviors: ['run', 'jump'], tags: ['户外', '释放'], priority: 7 },

  // ============================ 沟通表达 COMMUNICATION ============================
  { category: 'COMMUNICATION', title: 'PECS 图片交换系统', content: '从交换单张图卡表达需求起步，逐步扩展到句子，为无口语或低口语儿童建立功能性沟通。', source: 'PECS', severity: 'LOW', target: 'ALL', applicableBehaviors: ['point'], tags: ['PECS', '图片'], reference: 'Bondy & Frost', priority: 9 },
  { category: 'COMMUNICATION', title: '扩大替代沟通 AAC', content: '为无口语儿童引入 AAC 设备/App，提供语音输出，显著降低因无法表达引发的挫折行为。', source: 'AAC', severity: 'MEDIUM', target: 'ALL', applicableBehaviors: ['shake_head'], tags: ['AAC', '语音输出'], priority: 9 },
  { category: 'COMMUNICATION', title: '平行描述式语言输入', content: '在孩子活动时旁白描述（你在搭积木），提供丰富可理解的语言模型，而非不断提问。', source: 'Hanen', severity: 'LOW', target: 'ALL', tags: ['旁白', '输入'], priority: 8 },
  { category: 'COMMUNICATION', title: '扩展孩子的语言', content: '当孩子说「车」时，扩展为「红色的车在跑」，每次多加一两个词，自然提升句长。', source: 'Hanen', severity: 'LOW', target: 'ALL', tags: ['扩展', '句长'], priority: 8 },
  { category: 'COMMUNICATION', title: '功能性沟通意图回应', content: '及时回应孩子任何沟通企图（手势、眼神、声音），强化「沟通有用」的信念，激发主动沟通。', source: 'PRT', severity: 'LOW', target: 'ALL', applicableBehaviors: ['point', 'wave'], tags: ['意图', '回应'], priority: 8 },
  { category: 'COMMUNICATION', title: '视觉时间表沟通', content: '用图卡时间表让孩子预知「接下来做什么」，减少因未知引发的不安与抗拒沟通。', source: 'TEACCH', severity: 'LOW', target: 'ALL', tags: ['时间表', '预告'], priority: 7 },
  { category: 'COMMUNICATION', title: '选择板减少挫败', content: '当孩子无法表达需求时提供二选一选择板，快速满足沟通，避免升级为情绪爆发。', source: 'PECS', severity: 'MEDIUM', target: 'ALL', applicableEmotions: ['angry', 'sad'], tags: ['选择板', '需求'], priority: 8 },
  { category: 'COMMUNICATION', title: '手势与口语并行', content: '在说词语同时做手势（吃→指嘴），多通道输入帮助理解，逐步撤除手势。', source: '-sign', severity: 'LOW', target: 'ALL', applicableBehaviors: ['point'], tags: ['手势', '并行'], priority: 7 },
  { category: 'COMMUNICATION', title: '沟通伙伴训练', content: '训练家长/教师在孩子沟通时放慢语速、等待 5 秒、蹲下平视，创造支持性沟通环境。', source: 'SCERTS', severity: 'LOW', target: 'ALL', tags: ['伙伴', '等待'], priority: 7 },
  { category: 'COMMUNICATION', title: '社交发起语言脚本', content: '提供「我想玩…」「帮我…」等发起语言脚本，贴于相应区域，提示主动表达。', source: 'PRT', severity: 'LOW', target: 'STUDENT', applicableBehaviors: ['point'], tags: ['发起', '脚本'], priority: 7 },
  { category: 'COMMUNICATION', title: '情绪词汇扩展', content: '除基本情绪外，逐步引入「失望、嫉妒、尴尬」等复杂情绪词，丰富情绪表达精度。', source: 'CBT', severity: 'LOW', target: 'STUDENT', applicableEmotions: ['sad', 'angry'], tags: ['词汇', '复杂情绪'], priority: 6 },
  { category: 'COMMUNICATION', title: '录音回放自纠', content: '录下孩子说话并一起回放，帮助其自我监控语速与清晰度，提升沟通有效性。', source: '言语治疗', severity: 'LOW', target: 'STUDENT', tags: ['录音', '自纠'], priority: 5 },
  { category: 'COMMUNICATION', title: '沟通功能行为分析', content: '当孩子用行为代替语言时，先判断其沟通功能（要东西/逃避/求关注），再用语言替代。', source: 'ABA', severity: 'MEDIUM', target: 'ALL', applicableBehaviors: ['shake_head', 'stamp'], tags: ['功能', '替代'], priority: 8 },
  { category: 'COMMUNICATION', title: '问答轮换练习', content: '用简单问答卡练习「问—答—等待」轮换，建立对话的基本节律与轮次意识。', source: 'ABA', severity: 'LOW', target: 'STUDENT', tags: ['问答', '轮换'], priority: 6 },
  { category: 'COMMUNICATION', title: '多模态沟通板', content: '整合图卡、文字、语音按钮的沟通板，适应不同场景与沟通伙伴，提升泛化。', source: 'AAC', severity: 'LOW', target: 'ALL', applicableBehaviors: ['point'], tags: ['多模态', '沟通板'], priority: 7 },
  { category: 'COMMUNICATION', title: '错误纠正策略', content: '孩子说错时不直接否定，而是示范正确说法让其复述，保护沟通动机。', source: 'Hanen', severity: 'LOW', target: 'ALL', tags: ['纠正', '示范'], priority: 6 },
  { category: 'COMMUNICATION', title: '需求表达优先', content: '优先教孩子表达最核心的需求（吃、玩、帮、停），这些高频功能沟通最能降低挫折。', source: 'PECS', severity: 'MEDIUM', target: 'ALL', applicableEmotions: ['angry'], tags: ['需求', '优先'], priority: 8 },
  { category: 'COMMUNICATION', title: '家庭沟通一致性', content: '全家使用一致的沟通方式（同一套图卡/手势），避免孩子在不同照料者间混淆。', source: '家庭系统', severity: 'LOW', target: 'PARENT', tags: ['一致', '家庭'], priority: 6 },

  // ============================ 家庭生活 FAMILY_LIFE ============================
  { category: 'FAMILY_LIFE', title: '家庭作息可视化', content: '用家庭公告板贴出每日作息图，让孩子预知洗澡、睡觉等节点，减少家庭冲突。', source: 'TEACCH', severity: 'LOW', target: 'PARENT', tags: ['作息', '可视化'], priority: 8 },
  { category: 'FAMILY_LIFE', title: '兄弟姐妹支持', content: '向典型发展 siblings 解释差异，安排专属亲子时间，避免其产生被忽视感与家庭紧张。', source: '家庭系统', severity: 'MEDIUM', target: 'PARENT', tags: ['兄弟姐妹', '支持'], priority: 7 },
  { category: 'FAMILY_LIFE', title: '家长情绪自我照护', content: '照料者需定期充电（短时独处、互助小组），避免耗竭，才能更好地支持孩子。', source: '家庭系统', severity: 'LOW', target: 'PARENT', tags: ['自我照护', '耗竭'], priority: 8 },
  { category: 'FAMILY_LIFE', title: '家庭任务分工', content: '明确父母/祖辈在干预中的角色分工，避免重复或冲突，形成合力。', source: '家庭系统', severity: 'LOW', target: 'PARENT', tags: ['分工', '合力'], priority: 6 },
  { category: 'FAMILY_LIFE', title: '就餐行为塑造', content: '对挑食/就餐困难，采用小步暴露（先接触、再闻、再尝），配合正向强化，避免餐桌对抗。', source: 'ABA', severity: 'MEDIUM', target: 'PARENT', applicableEmotions: ['disgust'], tags: ['就餐', '挑食'], priority: 7 },
  { category: 'FAMILY_LIFE', title: '就寝仪式建立', content: '固定睡前流程（洗澡—故事—灯暗），形成可预测仪式，帮助入睡困难儿童安定。', source: 'TEACCH', severity: 'LOW', target: 'PARENT', tags: ['就寝', '仪式'], priority: 7 },
  { category: 'FAMILY_LIFE', title: '公共场所预案', content: '外出前与孩子看社交故事预演流程，备好减压玩具，降低公共场所情绪失控风险。', source: '社交故事', severity: 'MEDIUM', target: 'PARENT', applicableEmotions: ['fear', 'angry'], tags: ['外出', '预案'], priority: 7 },
  { category: 'FAMILY_LIFE', title: '正向亲子互动时间', content: '每天 15 分钟「跟随孩子」的在地互动（Floortime），以孩子兴趣为支点深化关系。', source: 'DIR/Floortime', severity: 'LOW', target: 'PARENT', tags: ['亲子', '跟随'], priority: 8 },
  { category: 'FAMILY_LIFE', title: '家庭规则少而稳', content: '家庭规则宜少而稳定（3-5 条），全家一致执行，避免朝令夕改造成混乱。', source: 'PBS', severity: 'LOW', target: 'PARENT', tags: ['规则', '稳定'], priority: 6 },
  { category: 'FAMILY_LIFE', title: '情绪爆发家庭应对', content: '孩子情绪爆发时，家长先稳定自身情绪、保障安全、不急于说教，待平复后再复盘。', source: 'CBT', severity: 'MEDIUM', target: 'PARENT', applicableEmotions: ['angry', 'fear'], tags: ['爆发', '应对'], priority: 8 },
  { category: 'FAMILY_LIFE', title: '祖辈教养协同', content: '与祖辈沟通一致的干预理念与方法，减少隔代溺爱或方式冲突对孩子的影响。', source: '家庭系统', severity: 'LOW', target: 'PARENT', tags: ['祖辈', '协同'], priority: 6 },
  { category: 'FAMILY_LIFE', title: '家庭正向关注', content: '刻意捕捉并描述孩子的正向行为（你今天自己收好了玩具），平衡纠正与肯定比例。', source: 'PBS', severity: 'LOW', target: 'PARENT', tags: ['正向', '关注'], priority: 7 },
  { category: 'FAMILY_LIFE', title: '电子媒体管理', content: '设定屏幕时间与内容规则，避免短视频过度刺激加重注意与情绪问题。', source: '循证育儿', severity: 'LOW', target: 'PARENT', tags: ['屏幕', '管理'], priority: 6 },
  { category: 'FAMILY_LIFE', title: '家庭会议机制', content: '每周简短家庭会议，让孩子用图卡表达感受与需求，培养家庭参与感。', source: '家庭系统', severity: 'LOW', target: 'PARENT', applicableEmotions: ['sad', 'angry'], tags: ['会议', '表达'], priority: 5 },
  { category: 'FAMILY_LIFE', title: '安全居家改造', content: '对自伤/冲动风险儿童，加装门窗锁、收好危险物品，建立物理安全底线。', source: 'PBS', severity: 'HIGH', target: 'PARENT', applicableBehaviors: ['self_injury'], tags: ['安全', '改造'], priority: 9 },
  { category: 'FAMILY_LIFE', title: '家长互助网络', content: '加入家长互助社群，分享经验与资源，降低孤立感并获得实用建议。', source: '家庭系统', severity: 'LOW', target: 'PARENT', tags: ['互助', '社群'], priority: 5 },

  // ============================ 学校适应 SCHOOL_ADAPTATION ============================
  { category: 'SCHOOL_ADAPTATION', title: '个别化教育计划 IEP', content: '依据评估结果制定 IEP，明确年度目标、服务频次与评量方式，是校内支持的法定框架。', source: 'IEP', severity: 'MEDIUM', target: 'TEACHER', tags: ['IEP', '目标'], priority: 9 },
  { category: 'SCHOOL_ADAPTATION', title: '资源教室运用', content: '合理运用资源教室进行抽离或巡回辅导，在最小限制环境中提供针对性支持。', source: '融合教育', severity: 'LOW', target: 'TEACHER', tags: ['资源教室', '融合'], priority: 7 },
  { category: 'SCHOOL_ADAPTATION', title: '课堂视觉提示', content: '在教室张贴流程图、规则图、任务步骤图，降低语言指令负担，提升遵从度。', source: 'TEACCH', severity: 'LOW', target: 'TEACHER', applicableBehaviors: ['leave_seat'], tags: ['视觉', '提示'], priority: 8 },
  { category: 'SCHOOL_ADAPTATION', title: '座位与环境安排', content: '将孩子安排在干扰少、靠近教师的座位，必要时用隔板减少视觉分心。', source: 'TEACCH', severity: 'LOW', target: 'TEACHER', applicableBehaviors: ['leave_seat', 'run'], tags: ['座位', '分心'], priority: 7 },
  { category: 'SCHOOL_ADAPTATION', title: '同伴小老师制', content: '指定稳定的同伴小老师协助过渡与活动，提升校园归属感与社会参与。', source: '融合教育', severity: 'LOW', target: 'TEACHER', tags: ['同伴', '小老师'], priority: 7 },
  { category: 'SCHOOL_ADAPTATION', title: '课间过渡支持', content: '用计时器与视觉提示管理课间过渡，安排先行组织者预告下节课，减少过渡抗拒。', source: 'TEACCH', severity: 'LOW', target: 'TEACHER', applicableBehaviors: ['leave_seat', 'run'], tags: ['过渡', '预告'], priority: 7 },
  { category: 'SCHOOL_ADAPTATION', title: '作业量分层', content: '按能力分层布置作业，保证可完成性，避免因长期挫败产生拒学情绪。', source: 'IEP', severity: 'MEDIUM', target: 'TEACHER', applicableEmotions: ['sad', 'angry'], tags: ['作业', '分层'], priority: 7 },
  { category: 'SCHOOL_ADAPTATION', title: '校园危机预案', content: '对存在攻击/自伤风险的学生，校内制定危机预案，明确预警信号与应急分工。', source: 'PBS', severity: 'HIGH', target: 'TEACHER', applicableBehaviors: ['self_injury', 'stamp'], tags: ['校园', '危机'], priority: 9 },
  { category: 'SCHOOL_ADAPTATION', title: '社交技能小组课', content: '在资源教室开设社交技能小组，以游戏为载体系统练习问候、轮流、合作。', source: '社交故事', severity: 'LOW', target: 'TEACHER', tags: ['小组', '社交'], priority: 7 },
  { category: 'SCHOOL_ADAPTATION', title: '正向行为校内体系', content: '建立全校一致的正向行为支持(PBIS)三级体系，对特殊儿童与一般学生同样适用。', source: 'PBIS', severity: 'LOW', target: 'TEACHER', applicableBehaviors: ['stamp', 'leave_seat'], tags: ['PBIS', '全校'], priority: 7 },
  { category: 'SCHOOL_ADAPTATION', title: '家校沟通日志', content: '建立家校联络本/App，每日同步情绪、行为与作业，保证干预连续性。', source: '融合教育', severity: 'LOW', target: 'TEACHER', tags: ['家校', '日志'], priority: 7 },
  { category: 'SCHOOL_ADAPTATION', title: '考试与测评调适', content: '提供延长时限、单独考场、口头作答等合理调适，公平评估真实能力。', source: 'IEP', severity: 'LOW', target: 'TEACHER', tags: ['测评', '调适'], priority: 6 },
  { category: 'SCHOOL_ADAPTATION', title: '午餐与操场支持', content: '在结构化较弱的午餐/操场时段增派人员，预防同伴冲突与社交孤立。', source: '融合教育', severity: 'MEDIUM', target: 'TEACHER', applicableBehaviors: ['run', 'leave_seat'], tags: ['午餐', '操场'], priority: 6 },
  { category: 'SCHOOL_ADAPTATION', title: '兴趣特长融入', content: '将孩子的特殊兴趣（如恐龙、火车）融入教学与社交，提升参与度与同伴话题。', source: 'PRT', severity: 'LOW', target: 'TEACHER', tags: ['兴趣', '融入'], priority: 6 },
  { category: 'SCHOOL_ADAPTATION', title: '拒学行为干预', content: '对拒学，采用系统性脱敏（先短时到校、逐步延长）配合正向强化，而非强制。', source: 'CBT', severity: 'HIGH', target: 'TEACHER', applicableEmotions: ['fear', 'sad'], tags: ['拒学', '脱敏'], priority: 8 },
  { category: 'SCHOOL_ADAPTATION', title: '教师协作会诊', content: '班主任、资源教师、特教巡回辅导定期会诊，统一策略与数据记录口径。', source: '融合教育', severity: 'LOW', target: 'TEACHER', tags: ['会诊', '协作'], priority: 6 },
  { category: 'SCHOOL_ADAPTATION', title: '校园包容文化建设', content: '通过主题班会、同伴教育营造接纳差异的班级文化，减少欺凌与孤立。', source: '融合教育', severity: 'MEDIUM', target: 'TEACHER', tags: ['包容', '文化'], priority: 6 },
  { category: 'SCHOOL_ADAPTATION', title: '转衔与择业准备', content: '高年级起规划从学校到社会的转衔（职业培训、生活技能），提升长远独立性。', source: '转衔服务', severity: 'LOW', target: 'TEACHER', tags: ['转衔', '独立'], priority: 6 },

  // ============================ 危机干预 CRISIS_INTERVENTION ============================
  { category: 'CRISIS_INTERVENTION', title: '自伤行为即时处置', content: '发现自伤（撞头、咬手）立即移除伤害源、物理保护、保持冷静低语，绝不强化性关注，事后做功能分析。', source: 'PBS', severity: 'CRITICAL', target: 'ALL', applicableBehaviors: ['self_injury'], tags: ['自伤', '即时'], priority: 10 },
  { category: 'CRISIS_INTERVENTION', title: '危机降级非暴力沟通', content: '危机中避免对峙与肢体压制，用低音量、简短指令、提供选择，优先降级而非控制。', source: 'CPI', severity: 'HIGH', target: 'ALL', applicableBehaviors: ['self_injury', 'stamp'], tags: ['降级', '非暴力'], reference: 'CPI 危机预防', priority: 9 },
  { category: 'CRISIS_INTERVENTION', title: '物理安全防范', content: '危机期间确保环境无尖锐/易碎物品，人员保持安全距离但不围堵，预留撤离通道。', source: 'PBS', severity: 'CRITICAL', target: 'ALL', applicableBehaviors: ['self_injury'], tags: ['安全', '环境'], priority: 10 },
  { category: 'CRISIS_INTERVENTION', title: '紧急联系人机制', content: '建立包含家长、校医、心理老师的紧急联系链，危机发生 5 分钟内可启动多方支援。', source: 'PBS', severity: 'HIGH', target: 'ALL', applicableBehaviors: ['self_injury'], tags: ['联系人', '机制'], priority: 9 },
  { category: 'CRISIS_INTERVENTION', title: '危机后复盘会议', content: '危机平复 24 小时内召开复盘，分析触发、预警遗漏与处置得失，更新预防计划。', source: 'PBS', severity: 'HIGH', target: 'ALL', applicableBehaviors: ['self_injury', 'stamp'], tags: ['复盘', '更新'], priority: 8 },
  { category: 'CRISIS_INTERVENTION', title: '攻击行为防御姿势', content: '面对攻击，训练照料者采用标准防御姿势保护要害，避免激化的擒抱动作。', source: 'CPI', severity: 'HIGH', target: 'ALL', applicableBehaviors: ['stamp', 'self_injury'], tags: ['防御', '姿势'], priority: 8 },
  { category: 'CRISIS_INTERVENTION', title: '情绪急救七步', content: '危机通用七步：保障安全→降噪→低语→给空间→不争论→观察→记录，系统化稳定现场。', source: '危机干预', severity: 'HIGH', target: 'ALL', applicableEmotions: ['angry', 'fear'], tags: ['急救', '七步'], priority: 8 },
  { category: 'CRISIS_INTERVENTION', title: '医疗转介红线', content: '出现持续自伤、自伤致伤、自杀言语、攻击致伤时，立即医疗/精神科转介，不延误。', source: '精神科', severity: 'CRITICAL', target: 'ALL', applicableBehaviors: ['self_injury'], tags: ['转介', '红线'], priority: 10 },
  { category: 'CRISIS_INTERVENTION', title: '药物与行为并重', content: '若已用药，行为干预仍不可停；记录药物时效与行为波动关联，供医生调整参考。', source: '多学科', severity: 'MEDIUM', target: 'ALL', applicableBehaviors: ['self_injury', 'stamp'], tags: ['药物', '行为'], priority: 7 },
  { category: 'CRISIS_INTERVENTION', title: '危机预警信号清单', content: '列出该儿童专属预警（如特定重复动作、语速变化），早期识别比事后处置更关键。', source: 'PBS', severity: 'HIGH', target: 'ALL', applicableBehaviors: ['self_injury', 'spin'], tags: ['预警', '信号'], priority: 9 },
  { category: 'CRISIS_INTERVENTION', title: '逃避型危机处理', content: '当危机由任务逃避触发，平复后采用「先小步完成再奖励」逐步重建配合，而非放弃要求。', source: 'ABA', severity: 'MEDIUM', target: 'ALL', applicableBehaviors: ['stamp', 'shake_head'], tags: ['逃避', '重建'], priority: 7 },
  { category: 'CRISIS_INTERVENTION', title: '记录与法律合规', content: '危机事件需客观书面记录（时间、行为、处置、证人），既利于复盘也满足合规要求。', source: '合规', severity: 'MEDIUM', target: 'ALL', applicableBehaviors: ['self_injury'], tags: ['记录', '合规'], priority: 7 },
  { category: 'CRISIS_INTERVENTION', title: '照料者心理急救', content: '危机后照料者常受冲击，需简短心理急救（肯定、去罪责、安排轮休），维持长期支持力。', source: '心理急救', severity: 'MEDIUM', target: 'ALL', tags: ['照料者', '急救'], priority: 7 },
  { category: 'CRISIS_INTERVENTION', title: '校园暴力零容忍', content: '对针对他人的攻击行为，校园须即时隔离双方、保护受害者、启动行为干预与家校联动。', source: '校园安全', severity: 'HIGH', target: 'TEACHER', applicableBehaviors: ['stamp', 'self_injury'], tags: ['暴力', '零容忍'], priority: 8 },
  { category: 'CRISIS_INTERVENTION', title: '走失与冲动防范', content: '对易冲动离座/奔跑儿童，公共与校园场景配备定位设备与一对一看管，预防走失。', source: 'PBS', severity: 'HIGH', target: 'ALL', applicableBehaviors: ['run', 'leave_seat'], tags: ['走失', '定位'], priority: 8 },
  { category: 'CRISIS_INTERVENTION', title: '事后回归计划', content: '危机后制定渐进回归计划（先短时、再常态），并安排同伴/教师主动接纳，避免标签化。', source: 'PBS', severity: 'MEDIUM', target: 'TEACHER', applicableBehaviors: ['self_injury'], tags: ['回归', '计划'], priority: 7 },

  // ============================ 家长指导 PARENT_GUIDANCE ============================
  { category: 'PARENT_GUIDANCE', title: '早期干预黄金期', content: '0-6 岁是大脑可塑性最强的干预期，越早开始密集干预，长期预后越好。', source: '循证', severity: 'LOW', target: 'PARENT', tags: ['早期', '黄金期'], priority: 9 },
  { category: 'PARENT_GUIDANCE', title: '家长培训赋能', content: '系统培训家长掌握 ABA/TEACCH 居家策略，使干预延伸到每天，效果远胜仅在机构。', source: '循证', severity: 'LOW', target: 'PARENT', tags: ['培训', '赋能'], priority: 9 },
  { category: 'PARENT_GUIDANCE', title: '避免误区：以管代教', content: '纠正「孩子不听话就严管」的误区，特殊儿童更多需要结构化教学而非单纯管教。', source: '循证', severity: 'LOW', target: 'PARENT', tags: ['误区', '教学'], priority: 7 },
  { category: 'PARENT_GUIDANCE', title: '选择循证机构', content: '选择干预机构时核查是否采用循证实践（ABA/ESDM/TEACCH）并有数据化记录。', source: '循证', severity: 'LOW', target: 'PARENT', tags: ['机构', '循证'], priority: 7 },
  { category: 'PARENT_GUIDANCE', title: '期望值合理设定', content: '基于评估结果设定阶梯式可达目标，避免过高期待带来亲子压力与倦怠。', source: '循证', severity: 'LOW', target: 'PARENT', tags: ['期望', '合理'], priority: 7 },
  { category: 'PARENT_GUIDANCE', title: '证据而非传闻', content: '面对「偏方/神奇疗法」保持警惕，以同行评议证据而非个案证言做决策。', source: '循证', severity: 'MEDIUM', target: 'PARENT', tags: ['证据', '甄别'], priority: 7 },
  { category: 'PARENT_GUIDANCE', title: '兄弟姐妹教养平衡', content: '在投入特殊儿童之余，保障对典型发展子女的关注与时间，维持家庭整体健康。', source: '家庭系统', severity: 'MEDIUM', target: 'PARENT', tags: ['平衡', '兄弟姐妹'], priority: 6 },
  { category: 'PARENT_GUIDANCE', title: '长期规划意识', content: '尽早考虑成年后的安置、职业与监护安排，财务与法律规划宜未雨绸缪。', source: '转衔服务', severity: 'LOW', target: 'PARENT', tags: ['长期', '规划'], priority: 6 },
  { category: 'PARENT_GUIDANCE', title: '家长互助与倡导', content: '参与家长组织与政策倡导，既获得支持也推动资源与包容环境改善。', source: '倡导', severity: 'LOW', target: 'PARENT', tags: ['互助', '倡导'], priority: 5 },
  { category: 'PARENT_GUIDANCE', title: '在家数据记录', content: '家长每日简单记录情绪与行为，形成趋势，比记忆更可靠地指导调整策略。', source: 'ABA', severity: 'LOW', target: 'PARENT', tags: ['数据', '在家'], priority: 7 },
  { category: 'PARENT_GUIDANCE', title: '与教师有效沟通', content: '用具体数据而非情绪与教师沟通，聚焦「我们希望孩子达到什么、如何配合」。', source: '融合教育', severity: 'LOW', target: 'PARENT', tags: ['沟通', '协作'], priority: 6 },
  { category: 'PARENT_GUIDANCE', title: '接纳与去污名', content: '接纳孩子的神经多样性，避免过度自责或隐瞒，正向身份有助孩子自尊发展。', source: '神经多样性', severity: 'LOW', target: 'PARENT', tags: ['接纳', '去污名'], priority: 7 },
  { category: 'PARENT_GUIDANCE', title: '危机资源储备', content: '家长提前储备危机资源（热线、定点医院、紧急联系人），做到有备无患。', source: 'PBS', severity: 'MEDIUM', target: 'PARENT', applicableBehaviors: ['self_injury'], tags: ['资源', '储备'], priority: 7 },
  { category: 'PARENT_GUIDANCE', title: '奖励而非贿赂', content: '区分「事先约定的奖励」与「事中妥协的贿赂」，前者塑造行为，后者强化要挟。', source: 'ABA', severity: 'LOW', target: 'PARENT', tags: ['奖励', '贿赂'], priority: 6 },
  { category: 'PARENT_GUIDANCE', title: '自我情绪示范', content: '家长以自身冷静处理挫折的方式为孩子示范情绪调节，言传不如身教。', source: 'CBT', severity: 'LOW', target: 'PARENT', applicableEmotions: ['angry'], tags: ['示范', '身教'], priority: 6 },
  { category: 'PARENT_GUIDANCE', title: '信息过载应对', content: '面对海量干预信息，家长宜固定 1-2 个可信来源，避免焦虑性信息过载。', source: '循证', severity: 'LOW', target: 'PARENT', tags: ['信息', '过载'], priority: 5 },
  { category: 'PARENT_GUIDANCE', title: '亲子游戏即干预', content: '把干预融入日常游戏与家务，孩子在自然情境中学习，比机械训练更易泛化。', source: 'DIR/Floortime', severity: 'LOW', target: 'PARENT', tags: ['游戏', '自然'], priority: 7 },
  { category: 'PARENT_GUIDANCE', title: '阶段性复评', content: '每 3-6 个月做阶段性复评，依据进展调整目标与强度，避免计划僵化。', source: '循证', severity: 'LOW', target: 'PARENT', tags: ['复评', '调整'], priority: 6 },

  // ============================ 教师策略 TEACHER_STRATEGY ============================
  { category: 'TEACHER_STRATEGY', title: '通用学习设计 UDL', content: '采用 UDL 提供多表征、多行动表达、多投入方式，让特殊儿童在普通课堂中自然获益。', source: 'UDL', severity: 'LOW', target: 'TEACHER', tags: ['UDL', '多通道'], priority: 8 },
  { category: 'TEACHER_STRATEGY', title: '差异化教学', content: '在同一目标下提供不同难度路径与材料，让每个孩子处于最近发展区内学习。', source: '维果茨基', severity: 'LOW', target: 'TEACHER', tags: ['差异化', 'ZPD'], priority: 8 },
  { category: 'TEACHER_STRATEGY', title: '明确具体指令', content: '用具体、正向指令（「把手放桌上」）替代模糊禁止（「别乱动」），提升遵从度。', source: 'ABA', severity: 'LOW', target: 'TEACHER', applicableBehaviors: ['leave_seat'], tags: ['指令', '具体'], priority: 8 },
  { category: 'TEACHER_STRATEGY', title: '先行组织者', content: '在新活动前用 1 分钟预告目标与步骤，降低认知负荷与不确定焦虑。', source: '教学策略', severity: 'LOW', target: 'TEACHER', applicableEmotions: ['fear'], tags: ['预告', '组织'], priority: 7 },
  { category: 'TEACHER_STRATEGY', title: '高频低量强化', content: '对低遵从儿童采用高频、低量的即时强化（具体赞美/贴纸），快速建立行为联结。', source: 'ABA', severity: 'LOW', target: 'TEACHER', tags: ['强化', '高频'], priority: 7 },
  { category: 'TEACHER_STRATEGY', title: '错误无批评纠正', content: '学生出错时用「再试一次」示范正确做法，避免公开批评损伤动机与自尊。', source: '教学策略', severity: 'LOW', target: 'TEACHER', applicableEmotions: ['sad'], tags: ['纠正', '动机'], priority: 7 },
  { category: 'TEACHER_STRATEGY', title: '任务分析与链式教学', content: '将复杂技能拆为小步骤链（如洗手：开水—打皂—搓洗—冲—关），逐步教学与串接。', source: 'ABA', severity: 'LOW', target: 'TEACHER', tags: ['任务分析', ' chaining'], priority: 8 },
  { category: 'TEACHER_STRATEGY', title: '视觉工作系统', content: '用「左边未完成—右边已完成」的视觉工作系统，让孩子独立完成作业序列。', source: 'TEACCH', severity: 'LOW', target: 'TEACHER', applicableBehaviors: ['leave_seat'], tags: ['视觉', '工作系统'], priority: 8 },
  { category: 'TEACHER_STRATEGY', title: '同伴示范学习', content: '安排能力较好同伴示范目标行为，利用观察学习带动特殊儿童模仿。', source: '建模', severity: 'LOW', target: 'TEACHER', tags: ['示范', '模仿'], priority: 6 },
  { category: 'TEACHER_STRATEGY', title: '课堂行为数据本', content: '教师备简易数据本，按频率/时长记录目标行为，指导教学调整而非凭感觉。', source: 'ABA', severity: 'LOW', target: 'TEACHER', applicableBehaviors: ['stamp', 'leave_seat'], tags: ['数据', '课堂'], priority: 7 },
  { category: 'TEACHER_STRATEGY', title: '弹性分组教学', content: '按当下能力而非固定标签弹性分组，让孩子在不同任务中与不同同伴合作。', source: '融合教育', severity: 'LOW', target: 'TEACHER', tags: ['分组', '弹性'], priority: 6 },
  { category: 'TEACHER_STRATEGY', title: '情绪温度计上墙', content: '教室设置可视化情绪温度计，鼓励孩子随时标注心情，便于早期支持。', source: 'CBT', severity: 'LOW', target: 'TEACHER', applicableEmotions: ['angry', 'sad', 'fear'], tags: ['温度计', '上墙'], priority: 6 },
  { category: 'TEACHER_STRATEGY', title: '正向班级氛围', content: '用班级惯例、合作游戏与共同目标营造安全感，降低特殊儿童的防御与抗拒。', source: 'PBIS', severity: 'LOW', target: 'TEACHER', tags: ['氛围', '安全'], priority: 6 },
  { category: 'TEACHER_STRATEGY', title: '个别化提示梯度', content: '提示从最少到最多（口头→手势→示范→肢体），尽量让孩子独立回应，避免过度辅助。', source: '教学策略', severity: 'LOW', target: 'TEACHER', applicableBehaviors: ['point'], tags: ['提示', '梯度'], priority: 7 },
  { category: 'TEACHER_STRATEGY', title: '专业协作网络', content: '教师主动联结特教、心理、言语、作业治疗形成协作网，单一视角难解复杂需求。', source: '多学科', severity: 'LOW', target: 'TEACHER', tags: ['协作', '多学科'], priority: 6 },
  { category: 'TEACHER_STRATEGY', title: '避免标签效应', content: '在班级中不以障碍标签定义孩子，强调其优势与进步，保护自我概念。', source: '融合教育', severity: 'MEDIUM', target: 'TEACHER', tags: ['标签', '优势'], priority: 7 },
  { category: 'TEACHER_STRATEGY', title: '课堂感官调节角', content: '在教室一隅设低刺激调节角，允许孩子短暂自我调节，减少离座与冲动。', source: '感觉统合', severity: 'LOW', target: 'TEACHER', applicableBehaviors: ['leave_seat'], tags: ['调节角', '感官'], priority: 6 },
  { category: 'TEACHER_STRATEGY', title: '家校目标对齐', content: '确保校内目标与家庭目标一致（如都练「表达需求」），加速技能泛化与巩固。', source: '融合教育', severity: 'LOW', target: 'TEACHER', tags: ['对齐', '家校'], priority: 6 },

  // ============================ 认知训练 COGNITIVE_TRAINING ============================
  { category: 'COGNITIVE_TRAINING', title: '执行功能训练', content: '通过「计划—组织—监控」小任务（如整理书包步骤）训练执行功能，改善冲动与无序。', source: 'CBT', severity: 'LOW', target: 'STUDENT', tags: ['执行功能', '计划'], priority: 7 },
  { category: 'COGNITIVE_TRAINING', title: '工作记忆游戏', content: '用「记忆翻牌」「指令递增」等游戏渐进提升工作记忆容量，支撑学业与遵从。', source: '认知训练', severity: 'LOW', target: 'STUDENT', tags: ['工作记忆', '游戏'], priority: 7 },
  { category: 'COGNITIVE_TRAINING', title: '注意力分段训练', content: '将注意任务分段（每段 5-10 分钟）并逐步延长，配合计时器与奖励，提升持续注意。', source: '认知训练', severity: 'LOW', target: 'STUDENT', applicableBehaviors: ['leave_seat'], tags: ['注意力', '分段'], priority: 7 },
  { category: 'COGNITIVE_TRAINING', title: '分类与排序练习', content: '用实物/图卡做分类、排序、配对，发展逻辑思维与概念组织能力。', source: '认知训练', severity: 'LOW', target: 'STUDENT', tags: ['分类', '排序'], priority: 6 },
  { category: 'COGNITIVE_TRAINING', title: '视觉搜索任务', content: '设计「找不同」「找隐藏物」任务，训练视觉注意与细节觉察，趣味化提升专注。', source: '认知训练', severity: 'LOW', target: 'STUDENT', tags: ['视觉', '搜索'], priority: 6 },
  { category: 'COGNITIVE_TRAINING', title: '因果推理故事', content: '用连环图讲「因为…所以…」故事，训练因果推理与事件理解。', source: '认知训练', severity: 'LOW', target: 'STUDENT', tags: ['因果', '推理'], priority: 6 },
  { category: 'COGNITIVE_TRAINING', title: '解决问题的五步法', content: '教孩子面对问题用五步：停—想—选—做—看结果，建立通用问题解决框架。', source: 'CBT', severity: 'LOW', target: 'STUDENT', applicableEmotions: ['angry'], tags: ['解决问题', '五步'], priority: 7 },
  { category: 'COGNITIVE_TRAINING', title: '认知弹性活动', content: '通过「换个玩法」「不同答案都对」活动，训练思维灵活性与接受变化。', source: '认知训练', severity: 'LOW', target: 'STUDENT', applicableEmotions: ['surprise'], tags: ['弹性', '灵活'], priority: 6 },
  { category: 'COGNITIVE_TRAINING', title: '时间概念可视化', content: '用计时器、日程条把抽象时间变可见，帮助孩子理解「马上/等一下/十分钟」。', source: 'TEACCH', severity: 'LOW', target: 'STUDENT', tags: ['时间', '可视化'], priority: 7 },
  { category: 'COGNITIVE_TRAINING', title: '元认知提问', content: '完成后问「你刚才怎么做的？哪里难？」，培养对自我思维的觉察（元认知）。', source: 'CBT', severity: 'LOW', target: 'STUDENT', tags: ['元认知', '觉察'], priority: 6 },
  { category: 'COGNITIVE_TRAINING', title: '数字与数量游戏', content: '用数豆子、分点心等生活化游戏建立数感，降低数学焦虑。', source: '认知训练', severity: 'LOW', target: 'STUDENT', tags: ['数感', '游戏'], priority: 6 },
  { category: 'COGNITIVE_TRAINING', title: '指令听觉记忆', content: '从「做两件事」渐进到多步指令，训练听觉接收与记忆，支撑课堂遵从。', source: '认知训练', severity: 'LOW', target: 'STUDENT', tags: ['听觉', '指令'], priority: 6 },
  { category: 'COGNITIVE_TRAINING', title: '规则理解与变通', content: '在掌握规则后引导「例外情况」，训练在坚持与变通间平衡，减少刻板。', source: '认知训练', severity: 'MEDIUM', target: 'STUDENT', tags: ['规则', '变通'], priority: 6 },
  { category: 'COGNITIVE_TRAINING', title: '游戏化专注训练', content: '用积分闯关类专注训练 App，将枯燥练习游戏化，提升依从与重复频次。', source: '认知训练', severity: 'LOW', target: 'STUDENT', tags: ['游戏化', '专注'], priority: 5 },
  { category: 'COGNITIVE_TRAINING', title: '书写前准备', content: '通过捏泥、串珠等精细动作活动为书写做准备，避免过早机械抄写引发挫败。', source: '作业治疗', severity: 'LOW', target: 'STUDENT', tags: ['精细', '书写'], priority: 6 },
  { category: 'COGNITIVE_TRAINING', title: '认知训练个体化', content: '依据测评短板（记忆/注意/灵活）选择训练模块，避免一刀切，定期复测调优。', source: '认知训练', severity: 'LOW', target: 'ALL', tags: ['个体化', '测评'], priority: 6 },

  // ============================ 常规建立 ROUTINE_BUILDING ============================
  { category: 'ROUTINE_BUILDING', title: '可视化日程表', content: '用图片/文字日程表展示全天安排，孩子每完成一项自行移到「已完成」，建立掌控感。', source: 'TEACCH', severity: 'LOW', target: 'ALL', tags: ['日程', '可视化'], priority: 9 },
  { category: 'ROUTINE_BUILDING', title: '固定起床就寝时间', content: '固定每日起床与就寝时间，稳定生物钟，显著改善情绪与日间注意力。', source: '循证', severity: 'LOW', target: 'PARENT', tags: ['作息', '生物钟'], priority: 8 },
  { category: 'ROUTINE_BUILDING', title: '活动间过渡提示', content: '用计时器与倒数（还有 5 分钟结束）提示活动切换，减少过渡抗拒。', source: 'TEACCH', severity: 'LOW', target: 'ALL', applicableBehaviors: ['leave_seat'], tags: ['过渡', '提示'], priority: 8 },
  { category: 'ROUTINE_BUILDING', title: '自理流程卡', content: '为穿衣、洗漱、如厕制作步骤卡，逐步实现生活自理，减少依赖与冲突。', source: 'TEACCH', severity: 'LOW', target: 'ALL', tags: ['自理', '步骤卡'], priority: 8 },
  { category: 'ROUTINE_BUILDING', title: '先工作后奖励', content: '用「先完成再玩」的顺序安排，配合视觉计时，建立延迟满足与任务习惯。', source: 'ABA', severity: 'LOW', target: 'ALL', tags: ['先后', '奖励'], priority: 7 },
  { category: 'ROUTINE_BUILDING', title: '周末也保底 routine', content: '周末保持核心作息（起床、餐点）基本不变，避免周一返校剧烈波动。', source: '循证', severity: 'LOW', target: 'PARENT', tags: ['周末', '保底'], priority: 6 },
  { category: 'ROUTINE_BUILDING', title: '责任小岗位', content: '在家中/班级设固定小岗位（如发餐具、浇花），培养责任感与归属感。', source: '融合教育', severity: 'LOW', target: 'ALL', tags: ['责任', '岗位'], priority: 6 },
  { category: 'ROUTINE_BUILDING', title: '惯例 versus 强制', content: '把要求包装为「我们家/班的惯例」而非「听我的」，降低权力对抗。', source: 'PBS', severity: 'LOW', target: 'ALL', applicableEmotions: ['angry'], tags: ['惯例', '对抗'], priority: 7 },
  { category: 'ROUTINE_BUILDING', title: '收拾整理系统', content: '用标签收纳盒与照片标识，让孩子能独立归位物品，减少混乱与催促冲突。', source: 'TEACCH', severity: 'LOW', target: 'ALL', tags: ['收纳', '归位'], priority: 6 },
  { category: 'ROUTINE_BUILDING', title: '晨间启动流程', content: '设计 5 步晨间清单（起床—穿衣—洗漱—早餐—背包），用图示让孩子自主启动一天。', source: 'TEACCH', severity: 'LOW', target: 'PARENT', tags: ['晨间', '清单'], priority: 7 },
  { category: 'ROUTINE_BUILDING', title: '变化预告与备选', content: '当 routine 必须改变（如停课），提前预告并提供备选方案，降低焦虑。', source: 'TEACCH', severity: 'MEDIUM', target: 'ALL', applicableEmotions: ['fear', 'surprise'], tags: ['变化', '预告'], priority: 7 },
  { category: 'ROUTINE_BUILDING', title: '正向结束仪式', content: '每日结束用简短仪式（今天最棒的事）收尾，强化正向体验与稳定感。', source: '家庭系统', severity: 'LOW', target: 'PARENT', tags: ['结束', '仪式'], priority: 5 },
  { category: 'ROUTINE_BUILDING', title: '校内一日可视化', content: '在教室用磁贴日程让孩子自己移动「现在/接下来」，提升对校园生活的预测力。', source: 'TEACCH', severity: 'LOW', target: 'TEACHER', applicableBehaviors: ['leave_seat'], tags: ['校内', '可视化'], priority: 7 },
  { category: 'ROUTINE_BUILDING', title: '弹性中的结构', content: '在总体结构稳定前提下，偶尔引入小变化训练适应力，平衡稳定与灵活。', source: '认知训练', severity: 'LOW', target: 'ALL', tags: ['弹性', '结构'], priority: 5 },
  { category: 'ROUTINE_BUILDING', title: '完成打卡激励', content: '用周打卡表记录 routine 完成情况，集满兑换偏好活动，固化良好习惯。', source: 'ABA', severity: 'LOW', target: 'ALL', tags: ['打卡', '激励'], priority: 6 },
  { category: 'ROUTINE_BUILDING', title: '全家同步节奏', content: '尽量让主要照料者的接送与作息同步，避免孩子在不同节奏间频繁切换。', source: '家庭系统', severity: 'LOW', target: 'PARENT', tags: ['同步', '节奏'], priority: 5 },
];
